volumes:
  animarte_db_storage:

networks:
  n8n_network:
    driver: bridge

services:
  animarte-db: 
    container_name: animarte-db 
    image: postgres:17
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${ANIMARTE_DB_USER}
      - POSTGRES_PASSWORD=${ANIMARTE_DB_PASSWORD}
      - POSTGRES_DB=${ANIMARTE_DB_NAME}
    ports:
      - "9083:5432"
    volumes:
      - animarte_db_storage:/var/lib/postgresql/data
    networks:
      - n8n_network